In [18]:
import numpy as np
import sys
import array

# Типы данных

x=1
print(type(x))
print(sys.getsizeof(x))

x = "Hello"
print(type(x))

x = True
print(type(x))

l1 = list([])
print(sys.getsizeof(l1))

l2 = list([1, 2, 3])
print(sys.getsizeof(l2))

l3 = list([1, "2", True]) # Падает скорость
print(sys.getsizeof(l2))

<class 'int'>
28
<class 'str'>
<class 'bool'>
56
88
88


In [2]:
#Массивы
a1 = array.array('i', [1, 2, 3]) #Коды типа; Тип, Элементы
print(sys.getsizeof(a1))
print(type(a1))

92
<class 'array.array'>


In [17]:
#Различные способы объявления массивов NumPy
a = np.array([1.23, 2, 3, 4, 5]) # Повышающее приведение типов
print(type(a), a)

a1 = np.array([1.23, 2, 3, 4, 5], dtype=int) # Явное приведение типов
print(type(a), a)

print("\n")

print(np.array([range(i, i+3) for i in [1, 2, 3, 4, 5, 6]]))
print(np.zeros(10, dtype=int))
print(np.ones((3,5), dtype=int))
print(np.full((4,5), 3.1415))
print(np.arange(0, 20, 2))
print(np.eye(4)) #Квадратная единичная матрица

<class 'numpy.ndarray'> [1.23 2.   3.   4.   5.  ]
<class 'numpy.ndarray'> [1 2 3 4 5]
[[1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]]
[0 0 0 0 0 0 0 0 0 0]
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[3.1415 3.1415 3.1415 3.1415 3.1415]
 [3.1415 3.1415 3.1415 3.1415 3.1415]
 [3.1415 3.1415 3.1415 3.1415 3.1415]
 [3.1415 3.1415 3.1415 3.1415 3.1415]]
[ 0  2  4  6  8 10 12 14 16 18]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [10]:
np.random.seed(1)
x1 = np.random.randint(10, size=3)
print(x1)
x2 = np.random.randint(10, size=(3,2))
print(x2)
x3 = np.random.randint(10, size=(3,2,1))
print(x3)

print(x3.ndim, x3.shape, x3.size) #Число размерностей, размер каждой размерности, общий размер

[5 8 9]
[[5 0]
 [0 1]
 [7 6]]
[[[9]
  [2]]

 [[4]
  [5]]

 [[2]
  [4]]]
3 (3, 2, 1) 6


In [29]:
#Индекс
a0 = np.array([1, 2, 3, 4, 5])
print(a[0], a[-2])
a = np.array([[1,2],
              [3,4]])
print(a[0,1])

a[1,0]=100
print(a)

a0[0] = 3.6
print(a0) #Тип при создании фиксирован

[1 2] [1 2]
2
[[  1   2]
 [100   4]]
[3 2 3 4 5]


In [33]:
#Cрезы и копии!!!
#Формат [s:f:st]
a0 = np.array([1, 2, 3, 4, 5])
print(a0[:3])
print(a0[2:])
print(a0[1:-1])
print(a0[::-1]) #Обратный порядок, минус меняет начало и конец местами

[1 2 3]
[3 4 5]
[2 3 4]
[5 4 3 2 1]


In [38]:
#Решейпы
a0 = np.arange(1, 13)
print(a0)
print(a0.reshape(2,6)) #Общий размер должен сохранятся

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [43]:
#Конкатенация
x = np.array([1, 2, 3])
y = np.array([4, 5])
z = np.array([6])

print(np.concatenate([x, y, z]))
y = np.array([4, 5, 6])
r1 = np.vstack([x,y])
print(r1)

print(np.hstack([r1, r1]))

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


In [45]:
#Вычисления с массивами

x = np.arange(1, 6)
print(x)
print(x*2 + 3)

[1 2 3 4 5]
[ 5  7  9 11 13]


In [62]:
#Универсальные функции (без тривиальных примеров) Унарные

x = np.arange(5)
y = np.zeros(10)
print(y)
np.cos(x, out=y[::2])
print(y)

print(x)
print(np.add.reduce(x))
print(np.add.accumulate(x))

#Бинарные универсальные функции
print(np.multiply.outer(x,x))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[ 1.          0.          0.54030231  0.         -0.41614684  0.
 -0.9899925   0.         -0.65364362  0.        ]
[0 1 2 3 4]
10
[ 0  1  3  6 10]
[[ 0  0  0  0  0]
 [ 0  1  2  3  4]
 [ 0  2  4  6  8]
 [ 0  3  6  9 12]
 [ 0  4  8 12 16]]
