In [2]:
import numpy as np
import pandas as pd

Строки и симолы индексируются метками а не только числовыми значениями

Основные типы данных

- Series
- DataFrame
- Index

## Series

Для создания можно использовать
- Списки Python
- Массивы Numpy
- Словари
- Скалярные значения

In [14]:
data = pd.Series([0.25, 0.5, 0.75, 1.0])
print(data)
print(type(data), "\n")

print(data.values)
print(type(data.values), "\n")

print(data.index)
print(type(data.index), '\n')

#Обращения
print(data[0])
print(data[1:3], "\n")

#Явное определение индексов
data = pd.Series([0.25, 0.5, 0.75, 1.0], index=['a', 'b', 'c', 'd'])
print(data['a'])
print(data['b':'d'])
print(type(data.index), "\n")

data = pd.Series([0.25, 0.5, 0.75, 1.0], index=[1, 10, 7, 'd']) #Разный тип индексов
print(data[10:"d"])

popuation_dict = {
    'city_1': 1000,
    'city_2': 1002,
    'city_3': 1003,
    'city_4': 1004,
    'city_5': 1005
}

popuation = pd.Series(popuation_dict)

print(popuation['city_1':'city_4'])

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64
<class 'pandas.core.series.Series'> 

[0.25 0.5  0.75 1.  ]
<class 'numpy.ndarray'> 

RangeIndex(start=0, stop=4, step=1)
<class 'pandas.core.indexes.range.RangeIndex'> 

0.25
1    0.50
2    0.75
dtype: float64 

0.25
b    0.50
c    0.75
d    1.00
dtype: float64
<class 'pandas.core.indexes.base.Index'> 

10    0.50
7     0.75
d     1.00
dtype: float64
city_1    1000
city_2    1002
city_3    1003
city_4    1004
dtype: int64


## DataFrame

Двумерный массив с явно определённыйми индексами
Можно смотреть как на упорядоченной множество несколько объектов Series

Могут быть созданы
- объекты Series
- Списки словарей
- словари объектов Series
- двумерный массив NumPy
- Структурированный массив NumPy

In [16]:
# Cогласование по ключам
population_dict = {
    'city_1': 1000,
    'city_2': 1002,
    'city_3': 1003,
    'city_4': 1004,
    'city_5': 1005
}
area_dict = {
    'city_1': 100,
    'city_2': 200,
    'city_3': 300,
    'city_4': 400,
    'city_5': 500
}

population = pd.Series(population_dict)
area = pd.Series(area_dict)

states = pd.DataFrame({
    "population1":population,
    "area1": area
})

print(states)
print(states.values)
print(states.index)
print(states.columns)
print(type(states.values))
print(type(states.index))
print(type(states.columns))

        population1  area1
city_1         1000    100
city_2         1002    200
city_3         1003    300
city_4         1004    400
city_5         1005    500
[[1000  100]
 [1002  200]
 [1003  300]
 [1004  400]
 [1005  500]]
Index(['city_1', 'city_2', 'city_3', 'city_4', 'city_5'], dtype='object')
Index(['population1', 'area1'], dtype='object')
<class 'numpy.ndarray'>
<class 'pandas.core.indexes.base.Index'>
<class 'pandas.core.indexes.base.Index'>


## Index

Это способ организации ссылки на данный объектов Series и DataFrame

Это мультимножество с наличием повторяющихся значений

Неизменяемый объект и следует соглашениям объекта Set

In [27]:
ind = pd.Index([2, 3, 5, 7, 11])
print(ind[::2])

indA = pd.Index([1, 2, 3, 4, 5])
indB = pd.Index([2, 3, 4, 5, 6])

print(indA.intersection(indB))

#Выборка данных из Series

data = pd.Series([0.25, 0.5, 0.75, 1.0], index=['a', 'b', 'c', 'd'])

print('a' in data)
print('z' in data)
print(data.keys())
print(list(data.items())) #Похоже на словарь

data['z'] = 1000
data['a'] = 100
print(data)

data = pd.Series([0.25, 0.5, 0.75, 1.0], index=['a', 'b', 'c', 'd'])
print(data)

print(data['a':'c'])
print(data[0:2])
print(data[(data > 0.5) & (data < 1)])
print(data[['a', 'd']])

Index([2, 5, 11], dtype='int64')
Index([2, 3, 4, 5], dtype='int64')
True
False
Index(['a', 'b', 'c', 'd'], dtype='object')
[('a', 0.25), ('b', 0.5), ('c', 0.75), ('d', 1.0)]
a     100.00
b       0.50
c       0.75
d       1.00
z    1000.00
dtype: float64
a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64
a    0.25
b    0.50
c    0.75
dtype: float64
a    0.25
b    0.50
dtype: float64
c    0.75
dtype: float64
a    0.25
d    1.00
dtype: float64


In [30]:
#Aтрибуты и индексаторы
data = pd.Series([0.25, 0.5, 0.75, 1.0], index=[1, 3, 10, 15])
print(data[1])
print(data.loc[1])
print(data.iloc[1])

0.25
0.25
0.5


In [33]:
#Выборка данных из Датафрейма
population_dict = {
    'city_1': 1000,
    'city_2': 1002,
    'city_3': 1003,
    'city_4': 1004,
    'city_5': 1005
}
area_dict = {
    'city_1': 100,
    'city_2': 200,
    'city_3': 300,
    'city_4': 400,
    'city_5': 500
}

population = pd.Series(population_dict)
area = pd.Series(area_dict)

data = pd.DataFrame({
    "population1":population,
    "area1": area
})

print(data['area1'])
print(data.area1) # Эти конструкции в общем случаее не равны

data['new'] = data['area1']
#Универсальные функции работают
data['newl'] = data['area1']/data['population1']
print(data)

city_1    100
city_2    200
city_3    300
city_4    400
city_5    500
Name: area1, dtype: int64
city_1    100
city_2    200
city_3    300
city_4    400
city_5    500
Name: area1, dtype: int64
        population1  area1  new      newl
city_1         1000    100  100  0.100000
city_2         1002    200  200  0.199601
city_3         1003    300  300  0.299103
city_4         1004    400  400  0.398406
city_5         1005    500  500  0.497512


In [44]:
#Двумерный NumPy массив
data = pd.DataFrame({
    "population1":population,
    "area1": area
})

print(data)
print(data.values[0]) #Обращение к строке
print(data.T)

#Атрибуты-индексаторы

print(data.iloc[:3, 1:2])
print(data.loc[:'city_4', :])
print(data.loc[data['population1'] > 102])

data.iloc[0,2] = 999

        population1  area1
city_1         1000    100
city_2         1002    200
city_3         1003    300
city_4         1004    400
city_5         1005    500
[1000  100]
             city_1  city_2  city_3  city_4  city_5
population1    1000    1002    1003    1004    1005
area1           100     200     300     400     500
        area1
city_1    100
city_2    200
city_3    300
        population1  area1
city_1         1000    100
city_2         1002    200
city_3         1003    300
city_4         1004    400
        population1  area1
city_1         1000    100
city_2         1002    200
city_3         1003    300
city_4         1004    400
city_5         1005    500


IndexError: iloc cannot enlarge its target object

In [46]:
rng = np.random.default_rng()
s = pd.Series(rng.integers(0, 10,4))
print(s)
print(np.exp(s))

0    8
1    5
2    7
3    8
dtype: int64
0    2980.957987
1     148.413159
2    1096.633158
3    2980.957987
dtype: float64


In [50]:
#Объединение серий и NaN значения
population_dict = {
    'city_1': 1000,
    'city_2': 1002,
    'city_3': 1003,
    'city_4': 1004,
    'city_52': 1005
}
area_dict = {
    'city_1': 100,
    'city_2': 200,
    'city_3': 300,
    'city_42': 400,
    'city_5': 500
}
population = pd.Series(population_dict)
area = pd.Series(area_dict)
data = pd.DataFrame({"area1":area, "population1":population})
print(data)

#Объединение фреймов серий и NaN значения

dfA = pd.DataFrame(rng.integers(0,10, (2,2)), columns=['a', 'b'])
dfB = pd.DataFrame(rng.integers(0,10, (3,3)), columns=['a', 'b', 'c'])

print(dfA + dfB)

         area1  population1
city_1   100.0       1000.0
city_2   200.0       1002.0
city_3   300.0       1003.0
city_4     NaN       1004.0
city_42  400.0          NaN
city_5   500.0          NaN
city_52    NaN       1005.0
     a     b   c
0  2.0  11.0 NaN
1  6.0   4.0 NaN
2  NaN   NaN NaN


In [55]:
rng = np.random.default_rng(1)
A = rng.integers(0, 10, (3,4))
print(A)
print(A - A[0])

df = pd.DataFrame(A, columns=['a', 'b', 'c', 'd'])
print(df)
print(df.iloc[0], "\n")
print(df - df.iloc[0], '\n')
print(df.iloc[0, ::2])
print(df - df.iloc[0, ::2])

[[4 5 7 9]
 [0 1 8 9]
 [2 3 8 4]]
[[ 0  0  0  0]
 [-4 -4  1  0]
 [-2 -2  1 -5]]
   a  b  c  d
0  4  5  7  9
1  0  1  8  9
2  2  3  8  4
a    4
b    5
c    7
d    9
Name: 0, dtype: int64 

   a  b  c  d
0  0  0  0  0
1 -4 -4  1  0
2 -2 -2  1 -5 

a    4
c    7
Name: 0, dtype: int64
     a   b    c   d
0  0.0 NaN  0.0 NaN
1 -4.0 NaN  1.0 NaN
2 -2.0 NaN  1.0 NaN


In [58]:
#NA-значения: NaN, null, -99999
#Индикатора Nan, None
#None - Объект(накладные расходы) не работает с сумированниме min и.т.д

#vall = np.array([1, None, 3])
vall = np.array([1, np.nan, 3])
print(np.sum(vall))
print(np.nansum(vall))

nan
4.0


In [79]:
x = pd.Series(range(5), dtype=int)
x[0] = None
x[1] = np.nan
print(x) # Одинаково отображаются

x1 = pd.Series(['a', 'b', 'c', 'd'])
x1[0] = None
x1[1] = np.nan
print(x1) # Отображаются по-разному

x2 = pd.Series([1, 2, 3, np.nan, None, pd.NA])
print(x2)

x3 = pd.Series([1, 2, 3, np.nan, None, pd.NA], dtype='Int32')
print(x3)
print(x3.isnull())
print(x3[x3.isnull()])

print(x3.dropna())

df = pd.DataFrame([
    [1, 2, 3, np.nan, None, pd.NA],
    [1, 2, 3, 4, 5, 6],
    [1, np.nan, 3, 4, np.nan, 6]
])

print(df, '\n')
print(df.dropna(), '\n') #axis = 0 default
print(df.dropna(axis=1), '\n')

#how
# - all - all NaN Values
# - any - хотя бы одно значение
# thresh = x - есть МИНИМУМ x НЕПУСТЫХ значений
print(df.dropna(axis=1, how='all'), '\n')
print(df.dropna(axis=1, how='any'))
print(df.dropna(axis=1, thresh=2))

0    NaN
1    NaN
2    2.0
3    3.0
4    4.0
dtype: float64
0    None
1     NaN
2       c
3       d
dtype: object
0       1
1       2
2       3
3     NaN
4    None
5    <NA>
dtype: object
0       1
1       2
2       3
3    <NA>
4    <NA>
5    <NA>
dtype: Int32
0    False
1    False
2    False
3     True
4     True
5     True
dtype: bool
3    <NA>
4    <NA>
5    <NA>
dtype: Int32
0    1
1    2
2    3
dtype: Int32
   0    1  2    3    4     5
0  1  2.0  3  NaN  NaN  <NA>
1  1  2.0  3  4.0  5.0     6
2  1  NaN  3  4.0  NaN     6 

   0    1  2    3    4  5
1  1  2.0  3  4.0  5.0  6 

   0  2
0  1  3
1  1  3
2  1  3 

   0    1  2    3    4     5
0  1  2.0  3  NaN  NaN  <NA>
1  1  2.0  3  4.0  5.0     6
2  1  NaN  3  4.0  NaN     6 

   0  2
0  1  3
1  1  3
2  1  3
   0    1  2    3     5
0  1  2.0  3  NaN  <NA>
1  1  2.0  3  4.0     6
2  1  NaN  3  4.0     6
