#### 1. Какие еще существуют коды типов?

|    Code     |        Type        | Size, bytes |
|:-----------:|:------------------:|:-----------:|
|      i      |     signed int     |      2      |
|  I (big i)  |    unsigned int    |      2      |
| l (small l) |    signed long     |      4      |
|  L (big l)  |   unsigned long    |      4      |
|      q      |  signed long long  |      8      |
|      Q      | unsigned long long |      8      |
|      f      |       float        |      4      |
|      d      |       double       |      8      |
|      b      |    signed char     |      1      |
|      B      |   unsigned char    |      1      |
|      h      |    signed short    |      2      |
|      H      |   unsigned short   |      2      |

#### 2. Напишите код, подобный приведенному выше, но с другим типом

In [104]:
import numpy as np
from sys import getsizeof
from array import array

x = array("d", [1.02, 1032421.414124, 1.42424324, 0.0424242, 1.424242124124124])
print(type(x))
print(getsizeof(x))

<class 'array.array'>
120


#### 3. Напишите код для создания массива с 5 значениями, располагающимися через равные интервалы в диапазоне от 0 до 1

In [21]:
a1 = np.linspace(0, 1, 5)
print(a1)

a2 = np.arange(0, 1.25, 0.25)
print(a2)

[0.   0.25 0.5  0.75 1.  ]
[0.   0.25 0.5  0.75 1.  ]


#### 4. Напишите код для создания массива с 5 равномерно распределенными случайными значениями в диапазоне от 0 до 1

In [53]:
a3 = np.random.rand(5)
print(a3)

[0.92972563 0.14781363 0.68312578 0.74991413 0.40875612]


#### 5. Напишите код для создания массива с 5 нормально распределенными случайными значениями с мат. ожиданием = 0 и дисперсией 1

In [107]:
normal = np.random.normal(size=5) #по умолчанию стандартное N(0,1)
print(normal)

normal = np.random.normal(2, 0.125, 5) # mu = 2; D=0.125^2 !!!!
print(normal)

[ 0.81859683 -0.86355146  2.33236273  0.91014086 -0.05613974]
[2.00049619 1.99927481 1.99948029 1.99879578 1.99946009]


#### 6. Напишите код для создания массива с 5 случайнвми целыми числами в от [0, 10)

In [52]:
a4 = np.random.randint(0, 10, 5)
print(a4)

[2 0 1 4 2]


#### 7. Написать код для создания срезов массива 3 на 4
- первые две строки и три столбца
- первые три строки и второй столбец
- все строки и столбцы в обратном порядке
- второй столбец
- третья строка

In [10]:
arr = np.array([
     [1, 2, 3, 4],
     [5, 6, 7, 8],
     [9, 10, 11, 12]
])
print(arr, "\n")
print(arr[:2,:3], "\n")
print(arr[:3,1], "\n")
print(arr[:,::-1], "\n")
print(arr[:,1], "\n")
print(arr[2,:], "\n")

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

[[1 2 3]
 [5 6 7]] 

[ 2  6 10] 

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]] 

[ 2  6 10] 

[ 9 10 11 12] 



#### 8. Продемонстрируйте, как сделать срез-копию

In [35]:
a1 = np.array([1, 2, 3, 4, 5, 6])
b = a1.copy()
b[0] = 0
print(a1, "\n") #Теперь это действительно копия

matrix = np.array([
     [1, 2, 3, 4],
     [5, 6, 7, 8],
     [9, 10, 11, 12]
])

a2 = matrix[:2, :].copy()
print(a2)
matrix[:, 0] = -10
matrix[0,:] = -10
print(a2, "\n")
print(matrix)

[1 2 3 4 5 6] 

[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3 4]
 [5 6 7 8]] 

[[-10 -10 -10 -10]
 [-10   6   7   8]
 [-10  10  11  12]]


#### 9. Продемонстрируйте использование newaxis для получения вектора-столбца и вектора-строки

In [38]:
A = np.arange(1, 13)
print(A)
r_vec = A[np.newaxis, :]
print(r_vec)
c_vec = A[:, np.newaxis]
print(c_vec)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4  5  6  7  8  9 10 11 12]]
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]]


#### 10. Разберитесь, как работает метод dstack

In [64]:
a = np.array([1, 2, 3, 4, 5, 6])
b = np.array([7, 8, 9, 10, 11, 12])

print(np.dstack([a, b]), "\n")

m1 = np.array([
     [1, 2, 3],
     [5, 6, 7],
     [9, 10, 11]
])
m2 = np.array([
     [1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]
])

print(np.dstack([m1, m2]), "\n")

# Метод будет создавать трехмерный массив
# Массив состоит из пар чисел, стоящих в одинаковых позициях.

[[[ 1  7]
  [ 2  8]
  [ 3  9]
  [ 4 10]
  [ 5 11]
  [ 6 12]]] 

[[[ 1  1]
  [ 2  2]
  [ 3  3]]

 [[ 5  4]
  [ 6  5]
  [ 7  6]]

 [[ 9  7]
  [10  8]
  [11  9]]] 



#### 11. Разберитесь, как работают методы split, vsplit, hsplit, dsplit

Будем разбирать только split, так как

vsplit = split при axis=0
hsplit = split при axis=1
dsplit = split при axis=2

axis=0 по умолчанию

In [93]:
a = [1, 2, 3, 4, 5, 6, 7, 8]
#axis=0
print(np.split(a, [3, 6,])) #Разделит массив на куски разных размеров.
print(np.split(a, [3, 6, 8])) # Конечный индекс+1 не пишем, иначе получим пустой кусок

a1, a2, a3 = np.split(m1, 3) # Разделение на 3 одинаоквых массива если такое возможно
print(a1, a2, a3, "\n") #матрица делится по строкам при axis = 0

print(np.split(m1, 3, axis=1), "\n") # Деление по столбцам

mm = np.dstack([m1, m2])
print(mm, "\n")
a1, a2 = np.split(mm, 2, axis=2) #Размерность массива больше равна чем 3
print(a1) #Угадаем что это за срез
print(mm[:, :,0]) #Деление произошло по последнему индексу. Имеется лишняя скобка, нужно сдеалть решейп
print(a1.reshape(3,3))


[array([1, 2, 3]), array([4, 5, 6]), array([7, 8])]
[array([1, 2, 3]), array([4, 5, 6]), array([7, 8]), array([], dtype=int64)]
[[1 2 3]] [[5 6 7]] [[ 9 10 11]] 

[array([[1],
       [5],
       [9]]), array([[ 2],
       [ 6],
       [10]]), array([[ 3],
       [ 7],
       [11]])] 

[[[ 1  1]
  [ 2  2]
  [ 3  3]]

 [[ 5  4]
  [ 6  5]
  [ 7  6]]

 [[ 9  7]
  [10  8]
  [11  9]]] 

[[[ 1]
  [ 2]
  [ 3]]

 [[ 5]
  [ 6]
  [ 7]]

 [[ 9]
  [10]
  [11]]]
[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]]
[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]]


#### 12. Привести пример использования всех универсальных функций, которые я привёл

In [103]:
x = np.arange(1,13)
print(x)
print(np.sin(x))
print(np.cos(x))
print(np.tan(x))
print(x/2)
print(x//2)
print(x%2)
print(-x)
print(np.log(x))
print(np.exp(x))
print(x**2)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155
  0.6569866   0.98935825  0.41211849 -0.54402111 -0.99999021 -0.53657292]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219  0.96017029
  0.75390225 -0.14550003 -0.91113026 -0.83907153  0.0044257   0.84385396]
[0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6. ]
[0 1 1 2 2 3 3 4 4 5 5 6]
[1 0 1 0 1 0 1 0 1 0 1 0]
[ -1  -2  -3  -4  -5  -6  -7  -8  -9 -10 -11 -12]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458 2.30258509 2.39789527 2.48490665]
[2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03
 8.10308393e+03 2.20264658e+04 5.98741417e+04 1.62754791e+05]
[  1   4   9  16  25  36  49  64  81 100 121 144]
