In [1]:
import numpy as np

#### 1. Что надо изменить в последнем примере, чтобы он заработал без ошибок (транслирование)?

Достаточно сделать решейп

In [3]:
a = np.ones((3,2)).reshape((2,3))
b = np.arange(3)

c = a + b
print(c)

[[1. 2. 3.]
 [1. 2. 3.]]


#### Пример для y. Вычислить количество элементов (по обоим размерностям), значения которых больше 3 и меньше 9

In [10]:
y = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10]
])

print(np.sum((y>3) & (y<9), axis=0))
print(np.sum((y>3) & (y<9), axis=1))

[1 1 1 1 1]
[2 3]
